package ResourceServer

import (
	"os"
	"regexp"
	"strings"
)

var (
	mimeTypeMapper = map[string]string{}
	suffixFinder   = regexp.MustCompile(`(\.|=)[0-9a-zA-Z]*$`)
)

func findMimeType(path string) (string, string) {
	// Check if is index page
	if strings.HasSuffix(path, "/") {
		return path + "index.html", mimeTypeMapper[".html"]
	}

	// Try to get suffix and find mime
	pathSuffix := suffixFinder.FindString(path)
	if pathSuffix != "" {
		if mimeType, found := mimeTypeMapper[pathSuffix]; found {
			return path, mimeType
		}
	} else {
		if _, err := os.Stat(path + "/index.html"); err == nil {
			return path + "/index.html", mimeTypeMapper[".html"]
		}
	}

	// Default if MIME-Type not found
	return path, "application/"
}

func init() {
	mimeTypeMapper = map[string]string{
		".dwg":     "application/acad",
		".asd":     "application/astound",
		".asn":     "application/astound",
		".tsp":     "application/dsptype",
		".dxf":     "application/dxf",
		".reg":     "application/force-download",
		".spl":     "application/futuresplash",
		".gz":      "application/gzip",
		".js":      "application/javascript",
		".json":    "application/json",
		".ptlk":    "application/listenup",
		".hqx":     "application/mac-binhex40",
		".mbd":     "application/mbedlet",
		".mif":     "application/mif",
		".xls":     "application/msexcel",
		".xla":     "application/msexcel",
		".chm":     "application/mshelp",
		".hlp":     "application/mshelp",
		".ppt":     "application/mspowerpoint",
		".ppz":     "application/mspowerpoint",
		".pps":     "application/mspowerpoint",
		".pot":     "application/mspowerpoint",
		".doc":     "application/msword",
		".dot":     "application/msword",
		".bin":     "application/octet-stream",
		".file":    "application/octet-stream",
		".com":     "application/octet-stream",
		".class":   "application/octet-stream",
		".ini":     "application/octet-stream",
		".oda":     "application/oda",
		".pdf":     "application/pdf",
		".ai":      "application/postscript",
		".eps":     "application/postscript",
		".ps":      "application/postscript",
		".rtc":     "application/rtc",
		".rtf":     "application/rtf",
		".smp":     "application/studiom",
		".tbk":     "application/toolbook",
		".odc":     "application/vnd.oasis.opendocument.chart",
		".odf":     "application/vnd.oasis.opendocument.formula",
		".odg":     "application/vnd.oasis.opendocument.graphics",
		".odi":     "application/vnd.oasis.opendocument.image",
		".odp":     "application/vnd.oasis.opendocument.presentation",
		".ods":     "application/vnd.oasis.opendocument.spreadsheet",
		".odt":     "application/vnd.oasis.opendocument.text",
		".odm":     "application/vnd.oasis.opendocument.text-master",
		".wmlc":    "application/vnd.wap.wmlc",
		".wmlsc":   "application/vnd.wap.wmlscriptc",
		".vmd":     "application/vocaltec-media-desc",
		".vmf":     "application/vocaltec-media-file",
		".bcpio":   "application/x-bcpio",
		".z":       "application/x-compress",
		".cpio":    "application/x-cpio",
		".csh":     "application/x-csh",
		".dcr":     "application/x-director",
		".dir":     "application/x-director",
		".dxr":     "application/x-director",
		".dvi":     "application/x-dvi",
		".evy":     "application/x-envoy",
		".gtar":    "application/x-gtar",
		".hdf":     "application/x-hdf",
		".php":     "application/x-httpd-php",
		".phtml":   "application/x-httpd-php",
		".latex":   "application/x-latex",
		".xml":     "application/xml",
		".nc":      "application/x-netcdf",
		".cdf":     "application/x-netcdf",
		".nsc":     "application/x-nschat",
		".sh":      "application/x-sh",
		".shar":    "application/x-shar",
		".swf":     "application/x-shockwave-flash",
		".cab":     "application/x-shockwave-flash",
		".spr":     "application/x-sprite",
		".sprite":  "application/x-sprite",
		".sit":     "application/x-stuffit",
		".sca":     "application/x-supercard",
		".sv4cpio": "application/x-sv4cpio",
		".sv4crc":  "application/x-sv4crc",
		".tar":     "application/x-tar",
		".tcl":     "application/x-tcl",
		".tex":     "application/x-tex",
		".texinfo": "application/x-texinfo",
		".texi":    "application/x-texinfo",
		".t":       "application/x-troff",
		".tr":      "application/x-troff",
		".roff":    "application/x-troff",
		".ustar":   "application/x-ustar",
		".src":     "application/x-wais-source",
		".zip":     "application/zip",
		".au":      "audio/basic",
		".snd":     "audio/basic",
		".es":      "audio/echospeech",
		".mp3":     "audio/mpeg",
		".tsi":     "audio/tsplayer",
		".vox":     "audio/voxware",
		".wav":     "audio/wav",
		".aif":     "audio/x-aiff",
		".aiff":    "audio/x-aiff",
		".aifc":    "audio/x-aiff",
		".dus":     "audio/x-dspeech",
		".cht":     "audio/x-dspeech",
		".mid":     "audio/x-midi",
		".midi":    "audio/x-midi",
		".mp2":     "audio/x-mpeg",
		".ram":     "audio/x-pn-realaudio",
		".ra":      "audio/x-pn-realaudio",
		".rpm":     "audio/x-pn-realaudio-plugin",
		".stream":  "audio/x-qt-stream",
		".dwf":     "drawing/x-dwf",
		".bmp":     "image/bmp",
		".cod":     "image/cis-cod",
		".ras":     "image/cmu-raster",
		".fif":     "image/fif",
		".gif":     "image/gif",
		".ief":     "image/ief",
		".jpeg":    "image/jpeg",
		".jpg":     "image/jpeg",
		".jpe":     "image/jpeg",
		".png":     "image/png",
		".svg":     "image/svg+xml",
		".tiff":    "image/tiff",
		".tif":     "image/tiff",
		".mcf":     "image/vasa",
		".wbmp":    "image/vnd.wap.wbmp",
		".fh4":     "image/x-freehand",
		".fh5":     "image/x-freehand",
		".fhc":     "image/x-freehand",
		".ico":     "image/x-icon",
		".pnm":     "image/x-portable-anymap",
		".pbm":     "image/x-portable-bitmap",
		".pgm":     "image/x-portable-graymap",
		".ppm":     "image/x-portable-pixmap",
		".rgb":     "image/x-rgb",
		".xwd":     "image/x-windowdump",
		".xbm":     "image/x-xbitmap",
		".xpm":     "image/x-xpixmap",
		".wrl":     "model/vrml",
		".ics":     "text/calendar",
		".csv":     "text/comma-separated-values",
		".css":     "text/css",
		".htm":     "text/html",
		".html":    "text/html",
		".shtml":   "text/html",
		".txt":     "text/plain",
		".rtx":     "text/richtext",
		".tsv":     "text/tab-separated-values",
		".wml":     "text/vnd.wap.wml",
		".wmls":    "text/vnd.wap.wmlscript",
		".etx":     "text/x-setext",
		".sgm":     "text/x-sgml",
		".sgml":    "text/x-sgml",
		".talk":    "text/x-speech",
		".spc":     "text/x-speech",
		".3gp":     "video/3gpp",
		".mp4":     "video/mp4",
		".mpeg":    "video/mpeg",
		".mpg":     "video/mpeg",
		".mpe":     "video/mpeg",
		".ogg":     "video/ogg",
		".ogv":     "video/ogg",
		".qt":      "video/quicktime",
		".mov":     "video/quicktime",
		".viv":     "video/vnd.vivo",
		".vivo":    "video/vnd.vivo",
		".webm":    "video/webm",
		".avi":     "video/x-msvideo",
		".movie":   "video/x-sgi-movie",
		".vts":     "workbook/formulaone",
		".vtts":    "workbook/formulaone",
		"=mf":      "x-world/x-3dmf",
		"=m":       "x-world/x-3dmf",
		".qd3d":    "x-world/x-3dmf",
		".qd3":     "x-world/x-3dmf",
	}
}
